# Generated by Django 5.1.6 on 2025-04-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tree',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
